# Generated by Django 2.1.4 on 2019-01-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('phone', models.IntegerField(max_length=15)),
                ('number', models.IntegerField()),
            ],
        ),
    ]
