# Generated by Django 2.1.4 on 2019-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190104_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.CharField(max_length=128),
        ),
    ]
